language: python

git:
  depth: 1

matrix:
  include:
    - name: "Linux - Latest TeX Live"
      env: TEST_SUITE=linux-latest
      os: linux
      sudo: required
      python: 2.7
    - name: "OS X - Latest TeX Live"
      env: TEST_SUITE=osx-latest
      os: osx
      sudo: required
      language: generic
      osx_image: xcode10
      before_install:
        - sw_vers
        - brew update
        - python2.7 --version
        - brew install libidn
        - brew install ghostscript
        - gs -v
        - brew install imagemagick
        - compare -version
        - brew install xpdf
        - pdfinfo -v || (exit 0)

install:
  - if [[ "$TEST_SUITE" == "linux-latest" ]]; then
      ci/travis-install-linux.sh;
    fi
  - if [[ "$TEST_SUITE" == "osx-latest" ]]; then
      ci/travis-install-osx.sh;
    fi
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script:
  - ci/travis-after.sh
