language: python

git:
  depth: 1

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: osx
      sudo: required
      language: generic
      osx_image: xcode8

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-install-linux.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ci/travis-install-osx.sh;
    fi
  - sudo -i texhash
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script:
  - ci/travis-after.sh
