language: python
python:
  - "2.7"
sudo: true
install:
  - ci/travis-install-linux.sh
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script:
  - echo "AFTER"
  - ci/travis-after.sh
