language: python

git:
  depth: 1

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: osx
      sudo: required
      language: generic
      osx_image: xcode8
      before_install:
        - sw_vers
        - brew update
        - brew uninstall --ignore-dependencies python
        - brew install python@2 --universal --framework
        - export PATH="$(brew --prefix python@2)/bin:$PATH"
        - python2.7 -v || (exit 0)
        - python2 -v || (exit 0)
        - python -v
        - brew install libidn
        - brew install ghostscript
        - gs -v
        - brew install imagemagick
        - compare -version
        - brew install xpdf
        - pdfinfo -v || (exit 0)
    - os: osx
      sudo: required
      language: generic
      osx_image: xcode10
      before_install:
        - sw_vers
        - brew update
        - python2.7 -v || (exit 0)
        - python2 -v || (exit 0)
        - python -v
        - brew install libidn
        - brew install ghostscript
        - gs -v
        - brew install imagemagick
        - compare -version
        - brew install xpdf
        - pdfinfo -v || (exit 0)

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-install-linux.sh;
      export PATH=/opt/texbin:$PATH;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ci/travis-install-osx.sh;
      export PATH=/Library/TeX/Distributions/Programs/texbin:$PATH;
    fi
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script:
  - ci/travis-after.sh
