language: python

git:
  depth: 10

jobs:
  include:
    - name: "Linux - Latest TeX Live"
      env:
        - TEST_SUITE=linux-latest
        - PYTHON=python
      os: linux
      python: 3.6
    - name: "Linux - TeX Live 2019"
      env:
        - TEST_SUITE=linux-tl2019
        - PYTHON=python
      os: linux
      python: 3.6
    - name: "OS X - Latest TeX Live"
      env:
        - TEST_SUITE=osx-latest
        - PYTHON=python3
      os: osx
      language: generic
      osx_image: xcode10
      before_install:
        - sw_vers
        - brew update
        - python3 --version
        - brew install libidn
        - brew install ghostscript
        - gs -v
        - brew install imagemagick
        - compare -version
        - pdfinfo -v || (exit 0)
    - name: "OS X - TeX Live 2019"
      env:
        - TEST_SUITE=osx-tl2019
        - PYTHON=python3
      os: osx
      language: generic
      osx_image: xcode10
      before_install:
        - sw_vers
        - brew update
        - python3 --version
        - brew install libidn
        - brew install ghostscript
        - gs -v
        - brew install imagemagick
        - compare -version
        - pdfinfo -v || (exit 0)

install:
  - ult-base/ci/travis_install_${TEST_SUITE}.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=/Library/TeX/Distributions/Programs/texbin:$PATH;
    fi
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test PYTHON=${PYTHON}
after_script:
  - ci/travis_after.sh
